apps/accounts/urls.py
from django.urls import include, path

app_name = "accounts"

urlpatterns = [
    path("", include("allauth.urls")),
]

apps/main/urls.py
from django.urls import path

from apps.main.views import index, about

app_name = "main"

urlpatterns = [
    path("", index, name="index"),
    path("about", about, name="about"),
]

apps/tasks/urls.py
from django.urls import path

from apps.tasks import views as v

app_name = "tasks"

urlpatterns = [
    path("", v.task_list, name="task-list"),
    path("create", v.task_add, name="task-add"),
    path("edit/<id>", v.task_edit, name="task-edit"),
    path("delete/<id>", v.task_delete, name="task-delete"),
    path("toggle/<id>", v.task_toggle, name="task-toggle"),
    path("detail/<id>", v.task_detail, name="task-detail"),
]

config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.admindocs import urls as admindocs_urls

from apps.main import urls as main_urls
from apps.tasks import urls as task_urls
# from apps.accounts import urls as accounts_urls

urlpatterns = [
    # Apps:
    path("", include(main_urls, namespace="main")),
    path("tasks/", include(task_urls, namespace="tasks")),
    path("accounts/", include("allauth.urls")),
    # django-admin:
    path("admin/doc/", include(admindocs_urls)),
    path("admin/", admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    # It is a good practice to have explicit index view
    # path('', index, name='index'),
]

apps/accounts/models.py
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    def __str__(self):
        return self.email

apps/tasks/models.py
from django.db import models
from django.contrib.auth import get_user_model

from core.database.models import BaseTimestampedModel

User = get_user_model()


class Task(BaseTimestampedModel):
    name = models.CharField(max_length=255)
    description = models.TextField()
    is_completed = models.BooleanField()
    user = models.ForeignKey(User, related_name="tasks", on_delete=models.CASCADE)

    def __str__(self) -> str:
        return "{}".format(self.name)

core/database/models.py
import uuid
from django.db import models


class BaseModel(models.Model):
    uuid = models.UUIDField(unique=True, editable=False, default=uuid.uuid4)

    class Meta:
        abstract = True


class BaseTimestampedModel(models.Model):
    uuid = models.UUIDField(unique=True, editable=False, default=uuid.uuid4)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    modified = models.DateTimeField(auto_now_add=False, auto_now=True)

    class Meta:
        abstract = True

apps/accounts/forms.py
from django.contrib.auth import get_user_model

from django.contrib.auth.forms import UserCreationForm, UserChangeForm

User = get_user_model()


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = (
            "email",
            "password",
        )


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = User
        fields = (
            "email",
            "username",
            "password",
        )

apps/tasks/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Column, Field, Layout, Row
from django import forms

from apps.tasks.models import Task


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ("name",)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_show_labels = False
        self.helper.layout = Layout(
            Row(
                Column(
                    Field("name", css_class="input input-bordered mr-5"),
                    css_class="mr-5",
                ),
                css_class="w-full",
            )
        )

    def clean_name(self) -> str:
        name: str = self.cleaned_data["name"]
        if Task.objects.filter(name=name).exclude(id=self.instance.id).exists():
            raise forms.ValidationError(f"A Task with the name {name} exists")
        return name

    def save(self, commit: bool = True) -> Task:
        task: Task = super().save(commit)
        task.save()
        return task

apps/main/views.py
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render
from django.contrib.auth.decorators import login_required


def index(request: HttpRequest) -> HttpResponse:
    """
    Main (or index) view.
    Returns rendered default page to the user.
    Typed with the help of ``django-stubs`` project.
    """
    return render(request, "main/index.html")


@login_required
def about(request: HttpRequest) -> HttpResponse:
    """
    Renders the about page.
    """
    return render(request, "main/about.html")

apps/tasks/views.py
import logging

from django.http import (
    Http404,
    HttpRequest,
    HttpResponse,
    HttpResponseRedirect,
    HttpResponseNotAllowed,
)
from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from apps.tasks.models import Task
from apps.tasks.forms import TaskForm

logger = logging.getLogger("tasks")


def get_task_or_404(id, user):
    try:
        obj = Task.objects.get(id=id, user=user)
        return obj
    except Exception:
        raise Http404


@login_required
def task_list(request: HttpRequest) -> HttpRequest:
    """
    Renders the task page.
    """
    context = {}
    context["tasks"] = Task.objects.filter(user=request.user).order_by("-created")

    return render(request, "tasks/index.html", context)


@login_required
def task_add(request: HttpRequest) -> HttpRequest:
    """ """
    logger.debug(request.POST["task"])

    tasks = Task.objects.filter(user=request.user).order_by("-created")
    if request.method == "POST":
        task = request.POST["task"]
        task = Task.objects.create(name=task, is_completed=False, user=request.user)
        task.save()

    return render(request, "tasks/partials/task-list.html", {"tasks": tasks})


@login_required
def task_edit(request: HttpRequest, id) -> HttpRequest:
    """ """
    context = {}
    obj = get_task_or_404(id, request.user)
    form = TaskForm(request.POST or None, instance=obj)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse("tasks:task-detail", kwargs={"id": obj.id}))

    context["form"] = form
    return render(request, "tasks/partials/task-edit.html", context)


@login_required
def task_delete(request: HttpRequest, id) -> HttpRequest:
    """ """
    obj = get_task_or_404(id, request.user)
    if request.method == "POST":
        obj.delete()
        return HttpResponse("")

    return HttpResponseNotAllowed(["POST"])


@login_required
def task_toggle(request: HttpRequest, id) -> HttpRequest:
    """ """
    task = get_task_or_404(id, request.user)
    if request.method == "POST":
        task.is_completed = not task.is_completed
        task.save()
        return render(request, "tasks/partials/task-detail.html", {"task": task})

    return HttpResponseNotAllowed(["POST"])


@login_required
def task_detail(request: HttpRequest, id) -> HttpRequest:
    """ """
    obj = get_task_or_404(id, request.user)
    return render(request, "tasks/partials/task-detail.html", {"task": obj})

apps/main/templates/main/about.html
<!-- about.html -->
{% extends "base.html" %}

{% block content %}

<h1 class="text-3xl font-bold">About</h1>

<p>
    Pariatur nulla fugiat deserunt excepteur excepteur sunt adipisicing labore excepteur non. Duis nulla ea proident. In esse nisi minim tempor id laboris ullamco aute reprehenderit aute labore exercitation incididunt eiusmod. Labore consequat ut qui cillum voluptate non sunt irure et cillum dolore pariatur eiusmod.
</p>

{% endblock content %}

apps/main/templates/main/index.html
<!-- index.html -->
{% extends "base.html" %}

{% block content %}

<div class="hero">
    <div class="hero-content text-center">
      <div class="max-w-md">
        <h1 class="text-5xl font-bold">Hello there</h1>
        <p class="py-6">Provident cupiditate voluptatem et in. Quaerat fugiat ut assumenda excepturi exercitationem quasi. In deleniti eaque aut repudiandae et a id nisi.</p>

        {% if user.is_authenticated %}
          <a class="btn btn-primary" href="{% url 'tasks:task-list' %}">Tasks</a>
        {% else %}
          <a class="btn btn-primary" href="{% url 'account_login' %}">Login</a>
        {%endif%}

      </div>
    </div>
  </div>

{% endblock content %}

apps/tasks/templates/tasks/index.html
{% extends "base.html" %}

{% block content %}

    <div class="min-h-screen mx-auto">
        <h1 class="text-3xl font-bold text-center">Tasks</h1>
        <div class="mt-8">
            {% include 'tasks/components/task-add.html' %}
        </div>
        <div id="task-list" class="my-5">
            {% include 'tasks/components/task-list.html' %}
        </div>
    </div>
    
{% endblock content %}

apps/tasks/templates/tasks/partials/task-add.html
<form
    class="flex w-full"
    hx-post="{% url 'tasks:task-add' %}"
    hx-target="#task-list"
    hx-swap="innerHTML"
    _="on htmx:afterRequest reset() me"
>
    {% csrf_token %}
    <input type="text" name="task" placeholder="Add your task here!" class="input input-bordered w-full mr-4" required/>
    <button class="btn flex-no-shrink" type="submit">Add</button>
</form>

apps/tasks/templates/tasks/partials/task-detail.html
<div hx-target="this" hx-swap="outerHTML">
    <div class="flex justify-between items-center border-b border-slate-200 py-3 px-2 border-l-4 border-l-transparent">
        <form>
            {% csrf_token %}
            <input
                type="checkbox"
                name="completed"
                {% if task.is_completed %} checked {% endif %}
                class="checkbox mr-3"
                hx-post="{% url 'tasks:task-toggle' id=task.id %}"
            />
        </form>

        <div class="w-full text-slate-500 {% if task.is_completed %} line-through {% endif %}">{{ task.name }}</div>
        <button
            class="btn btn-sm btn-outline flex-no-shrink mr-3 {% if task.is_completed %} hidden {% endif %}"
            hx-get="{% url 'tasks:task-edit' id=task.id %}"
        >
            Edit
        </button>
        <form>
            {% csrf_token %}
            <button
                class="btn btn-sm btn-outline btn-error flex-no-shrink"
                hx-post="{% url 'tasks:task-delete' id=task.id %}"
                hx-confirm="Are you sure?"
            >
                Remove
            </button>
        </form>
    </div>
</div>

apps/tasks/templates/tasks/partials/task-edit.html
{% load crispy_forms_tags %}

<div id="task-edit-form" hx-target="this" hx-swap="outerHTML">
    <form>
        {% csrf_token %}
        <div class="flex justify-between items-center border-b border-slate-200 py-3 px-2 border-l-4 border-l-transparent">
            {% crispy form %}        
    
            <button
                class="btn btn-success btn-sm btn-outline flex-no-shrink ml-5 mr-3"
                hx-post="{% url 'tasks:task-edit' id=form.instance.id %}"
            >
                Submit
            </button>
            <button
                class="btn btn-sm btn-outline btn-error flex-no-shrink"
                hx-get="{% url 'tasks:task-detail' id=form.instance.id %}"
            >
                Cancel
            <button>
            
            {% if form.name.errors %}<i>{{ form.name.errors }}</i>{% endif %}
        </div>
    </form>
</div>

apps/tasks/templates/tasks/partials/task-list.html
<div>
    {% for task in tasks %}
        {% include "tasks/components/task-detail.html" with task=task %}
    {% empty %}
        <div>No tasks yet.</div>
    {% endfor %}
</div>

apps/theme/templates/base.html
<!-- base.html -->
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
  <link rel="shortcut icon" href="https://www.djangoproject.com/favicon.ico">
  <title>Django</title>

  <!-- Hyperscript -->
  <script src="https://unpkg.com/hyperscript.org@0.9.7"></script>
  <!-- HTMX -->
  <script src="https://unpkg.com/htmx.org@1.8.4"></script>

  <link rel="stylesheet" href="{% static 'theme/styles.css' %}">
  {% block css %}{% endblock css %}

</head>

<body hx-boost="true">
  <div class="">
    {% include "includes/navbar.html" %}
    <div class="max-w-screen-lg mx-auto mt-8">
      {% block content %}{% endblock content %}
    </div>
  </div>

  {% block js %}{% endblock js %}
</body>

</html>

apps/theme/templates/base_error.html
<!-- base_error.html -->
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
  <link rel="shortcut icon" href="https://www.djangoproject.com/favicon.ico">
  <title>{% block title %}{% endblock title %}</title>

  <link rel="stylesheet" href="{% static 'theme/styles.css' %}">
  {% block css %}{% endblock css %}

</head>

<body>
  <div class="">
    <div class="max-w-screen-lg mx-auto">
      {% block content %}{% endblock content %}
    </div>
  </div>

  {% block js %}{% endblock js %}
</body>

</html>

apps/theme/templates/includes/navbar.html
{% load utils %}

<header>
  <div class="w-full bg-base-200 shadow-md">
    <div class="navbar max-w-screen-lg mx-auto">
      <div class="flex-1">
        <a class="btn btn-ghost uppercase text-xl underline" href="{% url 'main:index' %}">django-htmx</a>
      </div>
      <div class="flex-none">
        <ul class="menu menu-horizontal px-1">
          {% if user.is_authenticated %}
          <li><a class="{% get_active_class 'tasks:task-list' %}" href="{% url 'tasks:task-list' %}">Tasks</a></li>
          <li><a class="{% get_active_class 'main:about' %}" href="{% url 'main:about' %}">About</a></li>
          {% if user.is_superuser %}
            <li data="disable-htmx"><a target="_blank" href="{% url 'admin:index' %}">Admin</a></li>
          {% endif %}
          <li>
            <form method="post" action="{% url 'account_logout' %}">
              {% csrf_token %}
              <button type="submit" href="{% url 'account_logout' %}" hx-confirm="Are you sure to logout?">Logout</button>
            </form>
          </li>
          {% else %}
          <li><a class="{% get_active_class 'account_login' %}" href="{% url 'account_login' %}">Login</a></li>
          <li><a class="{% get_active_class 'account_signup' %}" href="{% url 'account_signup' %}">Signup</a></li>
          {% endif %}
        </ul>
    </div>
  </div>
</header>